config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'search' => 'games#search'
  get 'advanced-search' => 'games#advanced_search'

  get 'games/advanced-search' => 'games#advanced_search_form'
  get 'games/most-popular' => 'games#most_popular', as: :most_popular_games
  get 'games/most-owned'   => 'games#most_owned',   as: :most_owned_games
  get 'games/most-wanted'  => 'games#most_wanted',  as: :most_wanted_games

  resources :games
  resources :users, only: [:index, :show]

  post 'games/:id/comments' => 'comments#create'
  post 'games/:id/upvote'    => 'games#upvote', as: :upvote_game
  post 'games/:id/downvote'  => 'games#downvote', as: :downvote_game
  post 'comments/:id/upvote' => 'comments#upvote', as: :upvote_comment
  post 'comments/:id/downvote' => 'comments#downvote', as: :downvote_comment
  post 'users/:id/owned_games/:game' => 'users#owned_games'
  post 'users/:id/wanted_games/:wanted_game' => 'users#wanted_games'
  post 'users/:id/:buddy' => 'users#buddies'
  post 'users/:id/buddy/:buddy_id' => 'users#change_status'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  validates :user_id, presence: true
  validates :game_id, presence: true

  belongs_to :user
  belongs_to :game
  has_many :votes, :as => :votable

  def vote_count
    self.votes.inject(0) { |total, vote| total += vote.value }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!

  respond_to :html, :js, :json

  def create
  	@game = Game.find(params[:id])
  	@comment = Comment.new(comment_params)
  	@comment.assign_attributes(user_id: current_user.id, game_id: params[:id])
  	if request.xhr?
      @comment.save
      # implicit call to create.js.erb
    elsif @comment.save
  		redirect_to game_path(@game)
  	else
  		render :"games/show"
  	end
  end

  def upvote
    @comment = Comment.find(params[:id])
    @game = @comment.game
    @vote = Vote.find_or_initialize_by(user_id: current_user.id, votable_type: "Comment", votable_id: @comment.id)
    new_value = @vote.value + 1
    @vote.assign_attributes(value: new_value)
    @vote.save
    if request.xhr?
      #implicit call to upvote.js.erb
    else
      redirect_to game_path(@game)
    end
  end

  def downvote
    @comment = Comment.find(params[:id])
    @game = @comment.game
    @vote = Vote.find_or_initialize_by(user_id: current_user.id, votable_type: "Comment", votable_id: @comment.id)
    new_value = @vote.value - 1
    @vote.assign_attributes(value: new_value)
    @vote.save
    if request.xhr?
      #implicit call to downvote.js.erb
    else
      redirect_to game_path(@game)
    end
  end


  private

  def comment_params
  	params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<li class="comment pure-menu-item comment" id="comment<%= comment.id %>">
  <p><%= comment.body %> - <a href="/users/<%= comment.user.id %>"><%= comment.user.username %></a><br>
    <span id="vote-total-<%= comment.id %>">Vote total: <%= comment.vote_count %></span>
    <% if current_user %>
  	<%= link_to image_tag("1_14_up.png"), upvote_comment_path(comment), method: :post, remote: true %>
    <%= link_to image_tag("1_14_down.png"), downvote_comment_path(comment), method: :post, remote: true %>
  <% end %>
  </p>
</li>

app/views/comments/create.js.erb
$('#comments-on-game-<%= @game.id %>').prepend("<%= j (render @comment)  %>");
$('.comment-text-area').val('');

app/views/comments/downvote.js.erb
$('#vote-total-<%= @comment.id %>').html("Vote total: <%= @comment.vote_count %>")

app/views/comments/upvote.js.erb
$('#vote-total-<%= @comment.id %>').html("Vote total: <%= @comment.vote_count %>")