config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'search' => 'games#search'
  get 'advanced-search' => 'games#advanced_search'

  get 'games/advanced-search' => 'games#advanced_search_form'
  get 'games/most-popular' => 'games#most_popular', as: :most_popular_games
  get 'games/most-owned'   => 'games#most_owned',   as: :most_owned_games
  get 'games/most-wanted'  => 'games#most_wanted',  as: :most_wanted_games

  resources :games
  resources :users, only: [:index, :show]

  post 'games/:id/comments' => 'comments#create'
  post 'games/:id/upvote'    => 'games#upvote', as: :upvote_game
  post 'games/:id/downvote'  => 'games#downvote', as: :downvote_game
  post 'comments/:id/upvote' => 'comments#upvote', as: :upvote_comment
  post 'comments/:id/downvote' => 'comments#downvote', as: :downvote_comment
  post 'users/:id/owned_games/:game' => 'users#owned_games'
  post 'users/:id/wanted_games/:wanted_game' => 'users#wanted_games'
  post 'users/:id/:buddy' => 'users#buddies'
  post 'users/:id/buddy/:buddy_id' => 'users#change_status'

  root 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :title, presence: true
  validates :image_url, presence: true

  before_validation :set_image, on: :create

  has_many :comments
  has_many :votes, :as => :votable
  has_many :game_features
  has_many :mechanics, through: :game_features
  has_many :owned_games
  has_many :owners, through: :owned_games
  has_many :desired_games, foreign_key: "wanted_game_id"
  has_many :wanters, through: :desired_games

  def self.search(query)
    if query == ""
      Game.all
    else
      exact = Game.where('lower(title) = ?', query.downcase)
      fuzzy = Game.where('lower(title) LIKE ?', "%#{query.downcase}%")
      (exact + fuzzy).uniq
    end
  end

  def self.advanced_search(players, time, feature)
    results = []
    unless players == ""
      results = Game.where('min_players <= ? AND max_players >= ?', players, players)
    end
    unless time == ""
      results = results.where('average_time >= ? AND average_time <= ?', time.to_i - 15, time.to_i + 15)
    end
    unless feature == ""
      results = results.select { |game| game.mechanics.map { |mechanic| mechanic.trait }.include?(feature)}
    end
    results
  end

  def vote_count
    self.votes.inject(0) { |total, vote| total += vote.value }
  end

  private

  def set_image
    if self.image_url == ""
      self.image_url = "/images/sorry.jpg"
    end
    self.image_url ||= "/images/sorry.jpg"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include ApplicationHelper

  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :upvote]
  before_filter :check_admin_status, :only => [:edit, :update, :destroy]

  respond_to :html, :js, :json

  def index
    @games = Game.order("title")

    if request.xhr?
      render :filter
    else
      render :index
    end
  end

  def most_popular
    @games = Game.all.sort_by { |game| game.vote_count }.reverse

    if request.xhr?
      render :filter
    else
      render :index
    end
  end

  def most_owned
    @games = Game.all.sort_by { |game| game.owners.count }.reverse
    
    if request.xhr?
      render :filter
    else
      render :index
    end
  end

  def most_wanted
    @games = Game.all.sort_by { |game| game.wanters.count }.reverse
    
    if request.xhr?
      render :filter
    else
      render :index
    end
  end

  def show
    @comments = @game.comments.order("created_at DESC")
    @comment = Comment.new
  end

  def new
    @game = Game.new
    @mechanics = Mechanic.all
  end

  def create
    @mechanics = Mechanic.all
    mechanic_traits = params[:game].delete(:mechanics)
    @game = Game.new(game_params)
    if @game.save
      mechanic_traits.each do |mechanic_trait|
        unless mechanic_trait == ""
          mechanic = Mechanic.find_by(trait: mechanic_trait)
          GameFeature.create(game_id: @game.id, mechanic_id: mechanic.id)
        end
      end
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
    @mechanics = Mechanic.all
  end

  def update
    @mechanics = Mechanic.all
    mechanic_traits = params[:game].delete(:mechanics)
    if @game.update(game_params)
      @mechanics.each do |mechanic|
        if mechanic_traits.include?(mechanic.trait)
          GameFeature.find_or_create_by(game_id: @game.id, mechanic_id: mechanic.id)
        else
          game_feature = GameFeature.find_by(game_id: @game.id, mechanic_id: mechanic.id)
          game_feature.destroy if game_feature
        end
      end
      redirect_to game_path(@game)
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  def upvote
    @game = Game.find(params[:id])
    @vote = Vote.find_or_initialize_by(user_id: current_user.id, votable_type: "Game", votable_id: @game.id)
    new_value = @vote.value + 1
    @vote.assign_attributes(value: new_value)
    @vote.save
    if request.xhr?
      #implicit call to upvote.js.erb
    else
      redirect_to game_path(@game)
    end
  end

  def downvote
    @game = Game.find(params[:id])
    @vote = Vote.find_or_initialize_by(user_id: current_user.id, votable_type: "Game", votable_id: @game.id)
    new_value = @vote.value - 1
    @vote.assign_attributes(value: new_value)
    @vote.save
    if request.xhr?
      #implicit call to downvote.js.erb
    else
      redirect_to game_path(@game)
    end
  end

  def search
    @games = Game.search(params[:search])
    render :search_results
  end

  def advanced_search_form
    @mechanics = Mechanic.all
  end

  def advanced_search
    @games = Game.advanced_search(params[:players], params[:game_time], params[:mechanics])
    render :search_results
  end

  private
  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :description, :min_players, :max_players, :average_time, :image_url, :mechanics)
  end


end

app/views/games/_comment.html.erb
<div class="comment">
  <p><%= comment.body %></p>
  <p>Vote total: <%= comment.vote_total %></p>
</div>

app/views/games/_form.html.erb
<%= form_for @game do |f| %>

  <% if @game.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h3>

    <ul>
    <% @game.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p><%= f.label :title %>
  <%= f.text_field :title %></p><p>
  <%= f.label :description %>
  <%= f.text_area :description %></p><p>
  <%= f.label :min_players %>
  <%= f.number_field :min_players, :class => 'text_field', :step => 1, :min => 1 %></p><p>
  <%= f.label :max_players %>
  <%= f.number_field :max_players, :class => 'text_field', :step => 1, :min => 1 %></p><p>
  <%= f.label :average_time, "Average Time in Minutes" %>
  <%= f.number_field :average_time, :class => 'text_field', :step => 5, :min => 5 %></p><p>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %></p><p>
  <% possible_mechanics = [] %>
  <% @mechanics.each do |mechanic| %>
    <% possible_mechanics << [mechanic.trait, mechanic.trait] %>
  <% end %>
  <label for="game_mechanics">Mechanics (hold Ctrl or Cmd to select more than one)</label>
  <%= f.select :mechanics, possible_mechanics, {:prompt => ""}, { :multiple => true, :size => 7 } %></p><p>
  <%= f.submit %></p>

<% end %>

app/views/games/_game.html.erb
<div class="game-wrapper">
  <div class="game">
    <a href="/games/<%= game.id %>"><img class="game-img pure-img-responsive" src="<%= game.image_url %>" alt="<%= game.title %>" /></a>
    <div class="game-text">
      <h3><%= link_to "#{game.title}", game %></h3>
      <p>Players:
        <% if game.min_players == game.max_players %>
          <%= game.min_players %>
        <% else %>
          <%= game.min_players %>-<%= game.max_players %>
        <% end %>
      </p>
      <p>Average Time: <%= game.average_time %> minutes</p>
      <div class="game-forms">
      <% if current_user %>
        <% if current_user.games.include?(game) %>
           <%= button_to "Owned!", {controller: "users", action: "owned_games", id: current_user.id, game: game.id}, method: "post", remote: true, class: "own-button-#{game.id}", disabled: true %>
        <% else %>
          <%= button_to "Have It!", {controller: "users", action: "owned_games", id: current_user.id, game: game.id}, method: "post", remote: true, class: "own-button-#{game.id}" %>
        <% end %>
        <% if current_user.wanted_games.include?(game) %>
          <%= button_to "Wanted!", {controller: "users", action: "owned_games", id: current_user.id, game: game.id}, method: "post", remote: true, class: "want-button-#{game.id}", disabled: true %>
        <% else %>
          <%= button_to "Want It!", {controller: "users", action: "wanted_games", id: current_user.id, wanted_game: game.id}, method: "post", remote: true, class: "want-button-#{game.id}" %>
        <% end %>
      <% end %>
    </div>
    </div>
    <p class="votes-label">votes</p>
    <div class="game-votes">
      <%= game.vote_count %>
    </div>
  </div>
</div>

app/views/games/advanced_search_form.html.erb
<h2>Having a party and need to pick the perfect game?</h2>

<p>Enter the number of guests, desired game length, and/or the game type below, and we’ll search through our database for the ideal game for your get together!</p>

<%= form_tag(advanced_search_path, :method => "get") do %>
	<p><%= label_tag(:players, "Number of players:") %>
  <%= number_field_tag(:players) %></p>
  <p><%= label_tag(:game_time, "Approximate game time (in minutes)") %>
  <%= number_field_tag(:game_time) %></p>
  <p><label for="mechanics">Type</label>
  <%= select_tag "mechanics", options_from_collection_for_select(@mechanics, "trait", "trait"), {include_blank: true} %></p>
  <%= submit_tag("Search") %>
<% end %>

app/views/games/downvote.js.erb
$('.game-votes').html("<%= @game.vote_count %>");

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render 'form' %>
<%= link_to 'Delete Game', game_path(@game),
  method: :delete,
  data: { confirm: "The game will be lost forever. Are you sure?"} %>

<%= link_to 'Back', game_path(@game) %>

app/views/games/filter.js.erb
$("#games").html("<%= j ( render @games )  %>");

app/views/games/index.html.erb
<h1 class=" games-index partial-header">All Games</h1>
<div class="game-link-bar">
	<%= link_to "A-Z", { controller: 'games', action: 'index', remote: true } %>
	<%= link_to "Most Popular", { controller: 'games', action: 'most_popular', remote: true } %>
	<%= link_to "Most Owned", { controller: 'games', action: 'most_owned', remote: true } %>
	<%= link_to "Most Wanted", { controller: 'games', action: 'most_wanted', remote: true }%>
</div>
<br style="clear:both" />
<div id="games">
	<%= render @games %>
</div>
<p><%= link_to "Add a New Game", new_game_path %></p>

app/views/games/new.html.erb
<h1>Add Your Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/search_results.html.erb
<h1 class=" games-index partial-header">Matching Games</h1>
<br style="clear:both" />
<%= render @games %>

<% if @games.empty? %>
	<p>No matching games found.</p>
<% end %>

app/views/games/show.html.erb
<div class="pure-g">
 <div class=" pure-u-1 pure-u-md-1-3 game-wrapper">
  <div class="game">
    <img class="game-img pure-img-responsive" src="<%= @game.image_url %>" alt="<%= @game.title %>" />
    <div class="game-text">
      <h3><%= link_to "#{@game.title}", @game %></h3>
      <p>Players:
        <% if @game.min_players == @game.max_players %>
          <%= @game.min_players %>
        <% else %>
          <%= @game.min_players %>-<%= @game.max_players %>
        <% end %>
      </p>
      <p>Average Time: <%= @game.average_time %> minutes</p>
      <div class="game-forms">
      <% if current_user %>
        <% if current_user.games.include?(@game) %>
           <%= button_to "Owned!", {controller: "users", action: "owned_games", id: current_user.id, game: @game.id}, method: "post", remote: true, class: "own-button-#{@game.id}", disabled: true %>
        <% else %>
          <%= button_to "Have It!", {controller: "users", action: "owned_games", id: current_user.id, game: @game.id}, method: "post", remote: true, class: "own-button-#{@game.id}" %>
        <% end %>
        <% if current_user.wanted_games.include?(@game) %>
          <%= button_to "Wanted!", {controller: "users", action: "owned_games", id: current_user.id, game: @game.id}, method: "post", remote: true, class: "want-button-#{@game.id}", disabled: true %>
        <% else %>
          <%= button_to "Want It!", {controller: "users", action: "wanted_games", id: current_user.id, wanted_game: @game.id}, method: "post", remote: true, class: "want-button-#{@game.id}" %>
        <% end %>
      <% end %>
    </div>
    </div>
    <p class="votes-label">votes</p>
    <div class="game-votes">
      <%= @game.vote_count %>
    </div>
  </div>
 </div>
 <div class="game-description pure-u-1 pure-u-md-1-3">
   <p>Description: <%= @game.description %></p>
   <p>Features:</p>
     <ul>
       <% @game.mechanics.each do |mechanic| %>
         <li><%= mechanic.trait %></li>
       <% end %>
     </ul>
  <% if current_user %>
    <p>What’s your opinion about this game?</p>
    <p>Vote here:
    <%= link_to image_tag("1_14_up.png"), upvote_game_path(@game), method: :post, remote: true %>
    <%= link_to image_tag("1_14_down.png"), downvote_game_path(@game), method: :post, remote: true %></p>
  <% end %>

  <% if current_user && current_user.admin_privileges %>
    <p><%= button_to "Admin? Edit this game...", edit_game_path(@game), method: :get %></p>
  <% end %>
 </div>
 <div class="comment-table pure-u-1 pure-u-md-1-3">

  <h2>Comments:</h2>
  <div class="pure-menu pure-menu-scrollable custom-restricted">
    <ul class="pure-menu-list" id="comments-on-game-<%= @game.id %>">
  <% if @game.comments.length > 0 %>
    <%= render @comments %>
  <% end %>
    </ul>
  </div>

  <% if current_user %>

    <h3>Add Comment:</h3>

    <%= form_tag("/games/#{@game.id}/comments", method: "post", remote: true) do %>

      <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h3>

        <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
      <% end %>

      <textarea class="comment-text-area" name="comment[body]"></textarea><br>
      <%= submit_tag("Add comment") %>
    <% end %>
  <% end %>
   </div>
</div>

app/views/games/upvote.js.erb
$('.game-votes').html("<%= @game.vote_count %>");