config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'search' => 'games#search'
  get 'advanced-search' => 'games#advanced_search'

  get 'games/advanced-search' => 'games#advanced_search_form'
  get 'games/most-popular' => 'games#most_popular', as: :most_popular_games
  get 'games/most-owned'   => 'games#most_owned',   as: :most_owned_games
  get 'games/most-wanted'  => 'games#most_wanted',  as: :most_wanted_games

  resources :games
  resources :users, only: [:index, :show]

  post 'games/:id/comments' => 'comments#create'
  post 'games/:id/upvote'    => 'games#upvote', as: :upvote_game
  post 'games/:id/downvote'  => 'games#downvote', as: :downvote_game
  post 'comments/:id/upvote' => 'comments#upvote', as: :upvote_comment
  post 'comments/:id/downvote' => 'comments#downvote', as: :downvote_comment
  post 'users/:id/owned_games/:game' => 'users#owned_games'
  post 'users/:id/wanted_games/:wanted_game' => 'users#wanted_games'
  post 'users/:id/:buddy' => 'users#buddies'
  post 'users/:id/buddy/:buddy_id' => 'users#change_status'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link href='https://fonts.googleapis.com/css?family=Fredericka+the+Great|Henny+Penny|Loved+by+the+King|Cedarville+Cursive' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "http://yui.yahooapis.com/pure/0.6.0/pure-min.css" %>
  <!-- <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css"> -->
  <%= stylesheet_link_tag "http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css" %>
  <%= stylesheet_link_tag "side-menu" %>
  <%= stylesheet_link_tag "pure-custom" %>
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <title>Gamenight</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
 </head>
 <body>
   <div id="layout">
    <!-- Menu toggle -->
     <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
     </a>

     <div id="menu">
       <a href="/"><img id="logo" src="/images/moon cloud.png"></a>
        <div class="pure-menu">

            <ul class="pure-menu-list">

                <li class="menu-item-custom pure-menu-item">
                  <%= link_to "your profile", user_path(current_user || 0), {:class => "pure-menu-link"}%>
                </li>
                <li class="menu-item-custom pure-menu-item"><%= link_to "your buddies", user_path(current_user || 0, :query => "buddies"), {:class => "pure-menu-link"} %></li>
                <li class="menu-item-custom pure-menu-item" class="menu-item-divided pure-menu-selected">
                  <%= link_to "your games", user_path(current_user || 0, :query => "games"), {:class => "pure-menu-link"} %>
                </li>

                <li class="menu-item-custom pure-menu-item">
                  <%= link_to "your wishlist", user_path(current_user || 0, :query => "wanted games"), {:class => "pure-menu-link"} %>
                </li>
            </ul>
            <div class="pure-menu-heading"><img class="pure-image-responsive">Games</div>
            <ul class="pure-menu-list">
              <li class="menu-item-custom pure-menu-item"><a href="/games" class="pure-menu-link">all the games</a></li>
              <li class="menu-item-custom pure-menu-item">
                <%= form_tag(search_path, :method => "get", :class => "search-form") do %>
                  <%= text_field_tag :search, params[:search], class: "search-bar", placeholder: "Search by name..." %>
                  <button class="search-button" type="submit">Search</button>
                <% end %>
              </li>
              <li class="menu-item-custom pure-menu-item"><%= link_to "advanced search", games_advanced_search_path, class: "pure-menu-link" %></li>
            </ul>
        </div>
    </div>


  <div id="main">
    <nav class="pure-g nav-custom">
      <h6 class="user-login pure-u-1-4"></h6>
      <% if current_user %>
        <h6 class="user-login pure-u-1-4"><%= link_to "Welcome #{current_user.username}!", user_path(current_user) %></h6>
        <h6 class="user-login pure-u-1-4"><%= link_to "logout", destroy_user_session_path, method: :delete %></h6>
      <% else %>
        <h6 class="user-login pure-u-1-4"><%= link_to "signup", new_user_registration_path %></h6>
        <h6 class="user-login pure-u-1-4"><%= link_to "login", new_user_session_path %></h6>
      <% end %>

    </nav>
    <div class="title-bar">
    <h1 class="site-title">Gamenight</h1>
    <h5 class="site-subtitle">"who let the pawns out?"</h5>
    <img src="/images/dice-banner.jpg">
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
</div>
<footer class="pure-g">
    <a class="pure-u-4-5" href="https://github.com/chi-cicadas-2015/gamenight"><img class="pure-image-responsive" src="/images/0.png"></a>
</footer>
<script src="http://purecss.io/combo/1.18.13?/js/ui.js"></script>
</body>
</html>